[project]
authors = ["ImEins <mehdi.ramtakh@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "diffnote"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
