[project]
authors = [{name = "ImEins", email = "mehdi.ramtakh@gmail.com"}]
description = "A FastAPI-based REST API for a versioned note-taking app."
name = "diffnote"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = ["pydantic-settings>=2.8.1,<3", "fastapi-pagination>=0.12.34,<0.13"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-aarch64"]

[tool.pixi.tasks]
dev = "uvicorn src.main:app --reload --port 8000 --host 0.0.0.0"
serve = "uvicorn src.main:app"
test = "pytest -v"

[tool.pixi.dependencies]
fastapi = ">=0.115.11,<0.116"
sqlmodel = ">=0.0.24,<0.0.25"
mypy = ">=1.15.0,<2"
loguru = ">=0.7.2,<0.8"
asyncpg = ">=0.30.0,<0.31"
alembic = ">=1.15.1,<2"
psycopg2 = ">=2.9.9,<3"

[tool.pixi.environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }

[tool.pixi.feature.dev.dependencies]
ruff = "*"
pytest = "*"
pytest-asyncio = "*"
