"""Test

Revision ID: 216c8911047f
Revises: a9264e9e41c6
Create Date: 2025-03-12 12:20:11.408510

"""

from typing import Sequence

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '216c8911047f'
down_revision: str | None = 'a9264e9e41c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'note', 'created_at', existing_type=postgresql.TIMESTAMP(), type_=sa.DateTime(timezone=True), nullable=True
    )
    op.alter_column(
        'note',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        'noteversion',
        'version_number',
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default='1',
    )
    op.alter_column(
        'noteversion',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'noteversion',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        'noteversion', 'version_number', existing_type=sa.INTEGER(), nullable=True, existing_server_default='1'
    )
    op.alter_column(
        'note',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        'note', 'created_at', existing_type=sa.DateTime(timezone=True), type_=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
