"""create note version table

Revision ID: a9264e9e41c6
Revises: 3f1cf7726baf
Create Date: 2025-03-09 02:50:25.366060

"""

from typing import Sequence

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a9264e9e41c6'
down_revision: str | None = '3f1cf7726baf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'noteversion',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('note_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['note_id'],
            ['note.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noteversion')
    # ### end Alembic commands ###
